/*
 *  {{dateFixtureName}}.js
 *  Generated by: Mongoose-Fixture v{{version}}
 *
 */

     
// create your data doucments using object-literals
module.exports = [
    {
        _id:''
        name:''
        tags:[]
    },
    {
        _id:'',
        name:'',
        tags:[]
    }
];
