/*
 *  __dataFixtureName__.js
 *  Generated by: Mongoose-Fixture v__version__
 *
 */

     
// create your data documents using object-literals
module.exports = [
    { /* fill in fixture data here */ },
    { /* fill in fixture data here */ }
];
