/*
 *  File: __schemaFileName__
 *  Generated by: Mongoose-Fixture (v__version__)
 *
 *
 */

var mongoose = require('mongoose');

var schema = mongoose.Schema({
    /*
     *
     * This is an example, fillin with
     * Your own schema data

       _id:{type:String},
       name:{type:String},
       tags:{type:Array},
       score:{type:Number}
     *
     */


});

module.exports = mongoose.model('__schemaName__', schema);
