/*
 *  {{ schemaName }}.js
 *  Generated by: Mongoose-Fixture v{{ version }}
 *
 *  
 */

module.exports = function(mongoose){
        
    var {{ schemaName }} = mongoose.Schema({
        _id:{type:String},
        name:{type:String},
        tags:{type:Array},
        score:{type:Number}
    });

    return exportSchema;
};
