/*
 *  File: ProductSchema.js
 *  Generated by: Mongoose-Fixture (v0.3.1)
 *
 *
 */

module.exports = function(mongoose, conn){

    var exportSchema = mongoose.Schema({
        /*
           this is an example, fillin with
           your own schema data
        */
        _id:{type:String},
        name:{type:String},
        tags:{type:Array},
        score:{type:Number}
    });

    return exportSchema;
};
