/*
 *  File: ProductSchema.js
 *  Generated by: Mongoose-Fixture (v0.2.0)
 *
 *  
 */
var mongoose = require('mongoose');

var schema = mongoose.Schema({
    /* 
       this is an example, fillin with
       your own schema data
    */
    _id:{type:String},
    name:{type:String},
    tags:{type:Array},
    score:{type:Number}
});

module.exports = mongoose.model('Product', schema);
