/*
 *  File: ProductSchemaMock.js
 *  Generated by: Mongoose-Fixture (v0.4.0)
 *
 *
 */
module.exports = function(mongoose, conn){

    var exportSchema = mongoose.Schema({
        /*
           this is an example, fillin with
           your own schema data
        */
        name:{type:String},
        tags:{type:Array},
        score:{type:Number}
    });
    return {name:'Product', schema:exportSchema};
};
