/*
 *  File: ProductsBigMock.js
 *  Generated by: Mongoose-Fixture (v0.2.0)
 *
 */

// @callback must be returned
// expects (err, object)
// object can be an array of data-documents, or a kwarg['dataFixtures']

module.exports = function(mongoose, conn, callback){

    // standard callback error
    var error = null;

    // create your data documents using object-literals
    var fixture = [];
    
    var insertsCtr = 1000;
    for(var ctr=0; ctr<insertsCtr; ctr++){
    /*
     * Example of adding a data document/fixture item 
     */
        fixture.push({
            // by not defining an _id mongoose-fixture
            // will by default set a mongo ObjectID
            // defining one manually will override mongoDB
            name:'series'+ctr,
            tags:['test'+ctr,'data']
        });
    }
    
    // mongoose-fixture expects implementor to return
    // the callback passed in context
    return callback(error, fixture);
};
