/*
 *  File: ProductsObjectLitMock.js
 *  Generated by: Mongoose-Fixture (v0.2.0)
 *
 */

// @callback must be returned
// expects (err, object)
// object can be an array of data-documents, or a kwarg['dataFixtures']
module.exports = function(mongoose, conn, callback){

    // standard callback error
    var error = null;

    // create your data documents using object-literals
    var fixture = {};
    
    fixture.dataStub1 = {
        name:'series1',
        tags:['test','data']
    };
    
    fixture.dataStub2 = {
        name:'series2',
        tags:['hidy','tidy']
    };

    fixture.dataStub3 = {
        name:'series3',
        tags:['calp','yar']
    };
    
    // mongoose-fixture expects implementor to return
    // the callback passed in context
    return callback(error, fixture);
};
